# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Greetings' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftProtobuf', '~> 1.9.0'

  # Pods for Greetings

  target 'GreetingsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GreetingsUITests' do
    # Pods for testing
  end

end
